### ISSUE TITLE
when i prototype a object, what happend?

### ISSUE THREAD

**Issue by marcellowy** [log4js-node/log4js-node#817] opened 2018-12-09 04:46 UTC
when I add isObject function on Object.
`
Object.prototype.isObject = function(o) {
    if(Object.prototype.toString.call(o) == '[object Object]') {
        return true;
    }
    return false;
};
`

always get error ：appender "isObject" is not valid (must be an object with property "type")

**Comment by nomiddlename** [comment] 2018-12-11 06:19
That's caused by the configuration code in log4js trying to iterate over the properties of the config object, and not checking for whether it's a prototype. So, it's my fault - but generally speaking, messing around with the core prototypes in javascript is frowned upon (see [this article](https://humanwhocodes.com/blog/2010/03/02/maintainable-javascript-dont-modify-objects-you-down-own/) for more information). I'll try to get a fix for this included in the 4.x release.

**Comment by devoto13** [comment] 2018-12-23 17:42
I would say it is a correct behavior to iterate over prototype properties if these properties are declared as enumerable. If one wishes to extend prototype of the `Object` (which is a bad practice as @nomiddlename said) they should declare property as non-enumerable instead:

```
Object.defineProperty(Object.prototype, 'isObject', {
    enumerable: false, // this line is optional as false is the default value
    value: function(o) { if(Object.prototype.toString.call(o) == '[object Object]') { return true; } return false; }
});
```

**Comment by nomiddlename** [comment] 2019-01-24 21:32
Closing this one, as @devoto13 has provided a way around the problem.

**Closed by nomiddlename** 2019-01-24 21:32 UTC
Labels: good first issue
