### ISSUE TITLE
multiFile appender set timeout go wrong: no such file or directory

### ISSUE THREAD

**Issue by zhouruiruiruiyan** [log4js-node/log4js-node#1353] opened 2022-12-07 03:18 UTC
When I use multiFile appender set timeout and setInterval to write log。
multiFile appender timeout=setInterval  timeout,The program go wrong：no such file or directory
Screen capture:  
![企业微信截图_16703827194386](https://user-images.githubusercontent.com/86469122/206079687-c3c2da58-6bcb-4de9-8274-d237f42eb071.png)  
Program demo:  
[testlog4js.zip](https://github.com/log4js-node/log4js-node/files/10172522/testlog4js.zip)

**Comment by lamweili** [comment] 2022-12-27 05:30
Duplicate of #1352.

**Closed** 2022-12-27 08:56 UTC
Labels: bug, duplicate

**Comment by lamweili** [comment] 2022-12-27 09:19
The `streamroller` library has been updated from `3.1.3` to `3.1.4` which fixes this issue.
No release is required on `log4js-node` as it uses `streamroller@^3.1.3`, which should automatically update to `3.1.4`.

Please let me know if the issue persists or if it resolves the issue. Thanks!
