### ISSUE TITLE
Syntax Error with node FILE.js

### ISSUE THREAD

**Issue by SomeoneRandom1** [log4js-node/log4js-node#582] opened 2017-10-30 23:35 UTC
Hello, whoever can help me is a legend. I have been trying to fix this for days now. Of course I am not paying someone to make it because I would love to learn this stuff. I don't give up easily but its time for me to ask for help.

`
    out: { type: 'console' },
                            ^

SyntaxError: Unexpected token ,
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:576:28)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
`

**Comment by nomiddlename** [comment] 2017-10-30 23:48
Duplicate of #581 - closing this one.

Don't open new issues when you've already got one going for the same problem. Thanks.

**Closed by nomiddlename** 2017-10-30 23:48 UTC
