### ISSUE TITLE
karma, jasmine, typescript: Problem with log4js configuration

### ISSUE THREAD

**Issue by jocafi** [log4js-node/log4js-node#685] opened 2018-03-12 23:42 UTC
I am trying to run my unit test, but I receive the error below:

> Chrome 64.0.3282 (Mac OS X 10.12.6) ERROR
>   {
>     "message": "An error was thrown in afterAll\nError: Problem with log4js configuration: ({ appenders: { out: { type: 'console' } },\n    at <Jasmine>\n    at tests.forEach (/var/folders/r0/q3wy_02d37q2n5zkf513_hnw0000gn/T/karma-typescript-bundle-31931lLiSPkJ8RypR.js:1509:15)\n    at <Jasmine>\n    at Configuration.throwExceptionIf (/var/folders/r0/q3wy_02d37q2n5zkf513_hnw0000gn/T/karma-typescript-bundle-31931lLiSPkJ8RypR.js:1507:11)\n    at Configuration.tryLoading (/var/folders/r0/q3wy_02d37q2n5zkf513_hnw0000gn/T/karma-typescript-bundle-31931lLiSPkJ8RypR.js:1521:12)\n    at Configuration ...

My test class is very simple:

```
import { configure, getLogger, Logger } from "log4js";

describe("Logging Service", () => {
  let log: Logger;

  beforeAll(()=> {
    configure({
      appenders: {
        out: { type: 'console' }
      },
      categories: {
        default: {appenders: ['out'], level: 'info'}
      }
    });

    this.log = getLogger("LoggingService");
  });

  it("should log", () =>  {
    this.log.info("Test.");
  });
});
```

**Comment by cula** [comment] 2018-03-13 02:27
Please tell me the version of log4js version and mocha version.
I could not reproduce the problem with the following code. 
`
dependencies: {
     log4js: ^2.5.3,
     mocha: ^5.0.4
 }
`
`
const { configure, getLogger, Logger  } = require("log4js");

describe("Logging Service", () => {
    let log;
    beforeEach(()=> {
        configure({
            appenders: {
                out: { type: 'console'  }
            },
            categories: {
                default: {appenders: ['out'], level: 'info'}
            }
        });
        this.log = getLogger("LoggingService");
    });
    it("should log", () =>  {
        this.log.info("Test.");
    });
});
`
(Just replace `import` with `require` and replace `beforeAll` with `beforeEach` in your code.)

**Comment by jocafi** [comment] 2018-03-13 13:35
Hi @cula ,

 I am not using mocha. I am using Jasmine, instead.

I tried to run your code and got the error below:

> Chrome 64.0.3282 (Mac OS X 10.12.6) ERROR
>   {
>     "message": "An error was thrown in afterAll\nUncaught Error: Problem with log4js configuration: ({ appenders: { out: { type: 'console' } },\n  categories: { default: { appenders: [ 'out' ], level: 'info' } } }) - appender \"[object Object]\" could not be loaded (error was: Error: Can't find ./appenders/console [undefined] (required by <PROJECT_DIR>//node_modules/log4js/lib/configuration.js))",
>     "str": "An error was thrown in afterAll\nUncaught Error: Problem with log4js configuration: ({ appenders: { out: { type: 'console' } },\n  categories: { default: { appenders: [ 'out' ], level: 'info' } } }) - appender \"[object Object]\" could not be loaded (error was: Error: Can't find ./appenders/console [undefined] (required by <PROJECT_DIR>/node_modules/log4js/lib/configuration.js))"
>   }

 I am using the versions:
MacOS: 10.12.6
nodejs: 8.9.3
npm: 5.71

```
  "dependencies": {
    "@types/dotenv": "^4.0.2",
    "@types/node": "^9.4.7",
    "dotenv": "^5.0.1",
    "firebase": "^4.10.1",
    "log4js": "^2.5.3",
    "rxjs": "^5.5.6"
  },
  "devDependencies": {
    "@types/jasmine": "^2.8.6",
    "jasmine-core": "^3.1.0",
    "karma": "^2.0.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-jasmine": "^1.1.1",
    "karma-typescript": "^3.0.12",
    "rimraf": "^2.6.2",
    "ts-node": "^5.0.1",
    "typescript": "^2.7.2"
  }
```
**karma.conf.js**

```
module.exports = function(config) {
    config.set({
        autoWatch: true,
        frameworks: ["jasmine", "karma-typescript"],
        files: [
            { pattern: "src/**/*.ts" }, // *.tsx for React Jsx
            { pattern: "test/**/*.ts" }
        ],

        karmaTypescriptConfig: {
            tsconfig: "./tsconfig.test.json"
        },

        preprocessors: {
            "src/**/*.ts": ["karma-typescript", "coverage"], // *.tsx for React Jsx
            "test/**/*.ts": ["karma-typescript"]
        },
        reporters: ["progress", "coverage", "karma-typescript"],
        browsers: ["Chrome"]
    });
};
```

**tsconfig.test.json**

```
{
    "compilerOptions": {
        "module": "commonjs",
        "esModuleInterop": true,
        "target": "es2015",
        "declaration": true,
        "noImplicitAny": true,
        "moduleResolution": "node",
        "sourceMap": true,
        "outDir": "dist",
        "baseUrl": ".",
        "paths": {
            "*": [
                "node_modules/*",
                "src/types/*"
            ]
        }
    },
    "include": [
        "src/**/*",
        "test/**/*"
    ]
}
```

**Comment by cula** [comment] 2018-03-15 02:52
I use all the files u offered and installed jasmine to run the test. But I still could not repreduce it. The following is the ouput. 
![image](https://user-images.githubusercontent.com/5352723/37441961-d4cefab6-283e-11e8-9807-b5670782c847.png)

I used `./node_modules/.bin/jasmine test/test-index.ts` to run the test.

**Comment by jocafi** [comment] 2018-03-18 19:17
@cula, thanks for your prompt reply.

Please, try to run `npm test` on my project below:

https://github.com/jocafi/logging-service-node

**Comment by cula** [comment] 2018-03-19 06:32
@jocafi 
Thank u very much. I pulled your code and reproduced it.

Problem:
Log4js does not support any browser environment while Karmas only support browser environment as showed in the `package.json` of Log4js and the doc of Karmas.

Workaround:
Just use only jasmine instead of karmas + jasmine.
Using [jasmine-ts](https://github.com/svi3c/jasmine-ts) to run your ts test case: `npm i --save-dev jasmine-ts`
Change `npm test` to `jasmine-test test/*.ts`

**Comment by jocafi** [comment] 2018-03-19 08:38
@cula , 
Many thanks to check it and find out what was going on.

I will use jasmine-ts as you suggested. 

BTW, I think you would like to say that Log4js support browsers, but the project Log4js-node does not. ;-)

Thank you for the help.

**Comment by cula** [comment] 2018-03-19 10:46
> BTW, I think you would like to say that Log4js support browsers, but the project Log4js-node does not. ;-)

Yes. U are welcome.

I closed this issue.

**Closed** 2018-03-19 10:46 UTC
