### ISSUE TITLE
Import error when using ES6 module syntax

### ISSUE THREAD

**Issue by Sdator** [log4js-node/log4js-node#1063] opened 2021-02-24 09:40 UTC
Since my project has enabled `"type": "module"` in `package.json`, an error was thrown when I imported it.

If I remove `"type": "module"` and use the CJS module, all modules in my project will need to be rewritten. Is there a good solution? thank

The following is the error message:

```
import { configure, getLogger } from "log4js";
         ^^^^^^^^^
SyntaxError: Named export 'configure' not found. The requested module 'log4js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'log4js';
const { configure, getLogger } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:105:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:151:5)
    at async Loader.import (node:internal/modules/esm/loader:166:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
```

**Comment by kevintechie** [comment] 2021-06-17 17:22
Also missing from log4js-api.

**Comment by kricha** [comment] 2021-12-11 19:10
any news here?

**Comment by peteriman** [comment] 2022-02-01 17:15
Duplicate of #1009.

**Comment by peteriman** [comment] 2022-04-11 09:43
I think this is a documentation issue.
The documentation below was dated 5 years ago (https://github.com/log4js-node/log4js-node/commit/02c6ebbb2d000e2ac4c7b801725108fca7d4076c) and might have not been updated.

```typescript
import { configure, getLogger } from "log4js";
configure("./filename");
const logger = getLogger();
logger.level = "debug";
logger.debug("Some debug messages");

configure({
  appenders: { cheese: { type: "file", filename: "cheese.log" } },
  categories: { default: { appenders: ["cheese"], level: "error" } }
});
```


I have the updated documentation below. Let me know if it works.
```typescript
import log4js from 'log4js';

log4js.configure({
  appenders: { cheese: { type: "file", filename: "cheese.log" } },
  categories: { default: { appenders: ["cheese"], level: "error" } }
});

const logger = log4js.getLogger();
logger.level = "debug";
logger.debug("Some debug messages");
```

**Closed** 2022-04-11 12:55 UTC
Labels: documentation, duplicate

**Comment by peteriman** [comment] 2022-04-12 07:05
@kevintechie
> Also missing from log4js-api.

---

CJS
```javascript
const log4js = require('@log4js-node/log4js-api');
const logger = log4js.getLogger('my-library');
logger.info("Library starting up");
```
ESM
```typescript
import log4js from '@log4js-node/log4js-api';
const logger = log4js.getLogger('my-library');
logger.info("Library starting up");
```
