### ISSUE TITLE
Log level not logging in different files.

### ISSUE THREAD

**Issue by arun-awnics** [log4js-node/log4js-node#585] opened 2017-11-02 09:59 UTC
I am trying to log different levels of logs in different files. The application creates different files but not logging according to the levels. All the logs are written in default file.

Here is my configuration:

```
{
    "appenders": {
        "out": { "type": "stdout" },
        "debug": { "type": "dateFile", "filename": "logs/debug", "pattern": "-yyyy-MM-dd.log", "alwaysIncludePattern": true, "keepFileExt": true },
        "result": { "type": "dateFile", "filename": "logs/result", "pattern": "-yyyy-MM-dd.log", "alwaysIncludePattern": true, "keepFileExt": true },
        "error": { "type": "dateFile", "filename": "logs/error", "pattern": "-yyyy-MM-dd.log", "alwaysIncludePattern": true, "keepFileExt": true },
        "default": { "type": "dateFile", "filename": "logs/default", "pattern": "-yyyy-MM-dd.log", "alwaysIncludePattern": true, "keepFileExt": true },
        "warn": { "type": "dateFile", "filename": "logs/warn", "pattern": "-yyyy-MM-dd.log", "alwaysIncludePattern": true, "keepFileExt": true }
    },
    "categories": {
        "default": { "appenders": ["out", "default"], "level": "info" },
        "debug": { "appenders": ["debug"], "level": "debug" },
        "result": { "appenders": ["result"], "level": "info" },
        "error": { "appenders": ["error"], "level": "ERROR" },
        "warn": { "appenders": ["warn"], "level": "WARN" }
    }
}
```

**Comment by nomiddlename** [comment] 2017-11-02 21:17
The "debug", "result", etc categories will only get used if there is a logger for those categories, e.g.
```javascript
const logger = log4js.getLogger("result");
logger.debug("something"); // will not appear in the result log because min level is 'info'
logger.info("something else"); // will appear in the result log
```
To do what you want to do, I think you'll need to use the [log level filter](https://log4js-node.github.io/log4js-node/logLevelFilter.html)

**Comment by arun-awnics** [comment] 2017-11-03 05:06
I tried what you told but I still get the same behavior as before: Here is my config file: 
```
{
    "appenders": {
        "out": { "type": "stdout" },
        "debug": { "type": "dateFile", "filename": "logs/debug", "pattern": "-yyyy-MM-dd.log", "alwaysIncludePattern": true, "keepFileExt": true },
        "debug-filter": { "type": "logLevelFilter", "appender": "debug", "level": "debug" },
        "result": { "type": "dateFile", "filename": "logs/result", "pattern": "-yyyy-MM-dd.log", "alwaysIncludePattern": true, "keepFileExt": true },
        "result-filter": { "type": "logLevelFilter", "appender": "result", "level": "info" },
        "error": { "type": "dateFile", "filename": "logs/error", "pattern": "-yyyy-MM-dd.log", "alwaysIncludePattern": true, "keepFileExt": true },
        "error-filter": { "type": "logLevelFilter", "appender": "error", "level": "error" },
        "default": { "type": "dateFile", "filename": "logs/default", "pattern": "-yyyy-MM-dd.log", "alwaysIncludePattern": true, "keepFileExt": true },
        "warn": { "type": "dateFile", "filename": "logs/warn", "pattern": "-yyyy-MM-dd.log", "alwaysIncludePattern": true, "keepFileExt": true },
        "warn-filter": { "type": "logLevelFilter", "appender": "warn", "level": "warn" }
    },
    "categories": {
        "default": { "appenders": ["out", "default"], "level": "info" },
        "debug": { "appenders": ["debug", "debug-filter"], "level": "debug" },
        "result": { "appenders": ["result", "result-filter"], "level": "info" },
        "error": { "appenders": ["error", "error-filter"], "level": "error" },
        "warn": { "appenders": ["warn", "warn-filter"], "level": "warn" }
    }
}
```

I have also set loggers for testing various levels of logs, as below:
```
const log = log4js.getLogger("result");
log.info('Connection established successfully for MySQL');
log.error('This is an error');
log.warn('This is a warning');
log.debug('This is a debug statement');
log.fatal('This is fatal message');
```
But this doesn't help either. 

FYI, the logs are getting printed with color codes on the stdout, i.e., on the console as follows:

>[2017-11-03 10:25:45.227] [INFO] startup - Connection established successfully for MySQL
[2017-11-03 10:25:45.229] [ERROR] startup - This is an error
[2017-11-03 10:25:45.230] [WARN] startup - This is a warning
[2017-11-03 10:25:45.232] [FATAL] startup - This is fatal message

**Comment by ramicohen303** [comment] 2017-11-03 12:31
You need to make the following changes:
1. The result category should include all filter appenders and have the level set to debug.
2. Each result-filter appender should set both level and maxLevel to the same value.

Try this configuration:

{
    "appenders": {
        "out": { "type": "stdout" },
        "debug": { "type": "dateFile", "filename": "logs/debug", "pattern": "-yyyy-MM-dd.log", "alwaysIncludePattern": true, "keepFileExt": true },
        "debug-filter": { "type": "logLevelFilter", "appender": "debug", "level": "debug", "maxLevel": "debug" },
        "result": { "type": "dateFile", "filename": "logs/result", "pattern": "-yyyy-MM-dd.log", "alwaysIncludePattern": true, "keepFileExt": true },
        "result-filter": { "type": "logLevelFilter", "appender": "result", "level": "info", "maxLevel": "info" },
        "error": { "type": "dateFile", "filename": "logs/error", "pattern": "-yyyy-MM-dd.log", "alwaysIncludePattern": true, "keepFileExt": true },
        "error-filter": { "type": "logLevelFilter", "appender": "error", "level": "error", "maxLevel": "error" },
        "default": { "type": "dateFile", "filename": "logs/default", "pattern": "-yyyy-MM-dd.log", "alwaysIncludePattern": true, "keepFileExt": true },
        "warn": { "type": "dateFile", "filename": "logs/warn", "pattern": "-yyyy-MM-dd.log", "alwaysIncludePattern": true, "keepFileExt": true },
        "warn-filter": { "type": "logLevelFilter", "appender": "warn", "level": "warn", "maxLevel": "warn" }
    },
    "categories": {
        "default": { "appenders": ["out", "default"], "level": "info" },
        "debug": { "appenders": ["debug", "debug-filter"], "level": "debug" },
        "result": { "appenders": ["result-filter", "debug-filter", "error-filter", "warn-filter"], "level": "debug" },
        "error": { "appenders": ["error", "error-filter"], "level": "error" },
        "warn": { "appenders": ["warn", "warn-filter"], "level": "warn" }
    }
}

**Comment by arun-awnics** [comment] 2017-11-04 05:17
Hey @ramicohen303 , I tried what you suggested. It doesn't work either.

**Comment by arun-awnics** [comment] 2017-11-04 05:22
I have spent 3 days on this already. Kindly let me know if it possible to segregate my files according to the log level. If yes, please tell me how to do it. My config file looks like this: 

```
{
    "appenders": {
        "out": { "type": "stdout" },
        "debug": { "type": "dateFile", "filename": "logs/debug", "pattern": "-yyyy-MM-dd.log", "alwaysIncludePattern": true, "keepFileExt": true },
        "debug-filter": { "type": "logLevelFilter", "appender": "debug", "level": "debug", "maxLevel": "debug" },
        "result": { "type": "dateFile", "filename": "logs/result", "pattern": "-yyyy-MM-dd.log", "alwaysIncludePattern": true, "keepFileExt": true },
        "result-filter": { "type": "logLevelFilter", "appender": "result", "level": "info", "maxLevel": "info" },
        "error": { "type": "dateFile", "filename": "logs/error", "pattern": "-yyyy-MM-dd.log", "alwaysIncludePattern": true, "keepFileExt": true },
        "error-filter": { "type": "logLevelFilter", "appender": "error", "level": "error", "maxLevel": "error" },
        "default": { "type": "dateFile", "filename": "logs/default", "pattern": "-yyyy-MM-dd.log", "alwaysIncludePattern": true, "keepFileExt": true },
        "warn": { "type": "dateFile", "filename": "logs/warn", "pattern": "-yyyy-MM-dd.log", "alwaysIncludePattern": true, "keepFileExt": true },
        "warn-filter": { "type": "logLevelFilter", "appender": "warn", "level": "warn", "maxLevel": "warn" }
    },
    "categories": {
        "default": { "appenders": ["out", "default"], "level": "info" },
        "debug": { "appenders": ["debug", "debug-filter"], "level": "debug" },
        "result": { "appenders": ["result-filter", "debug-filter", "error-filter", "warn-filter"], "level": "debug" },
        "error": { "appenders": ["error", "error-filter"], "level": "error" },
        "warn": { "appenders": ["warn", "warn-filter"], "level": "warn" }
    }
}
```

**Comment by ramicohen303** [comment] 2017-11-04 20:10
[test.zip](https://github.com/log4js-node/log4js-node/files/1443536/test.zip)

Can you please be more specific as to the results you are getting? I created a super simple project with the code you provided, and attached it to this message. Please download the zip file, extract it, run 'npm install', run 'node index.js', and tell me what you get. What I see is:

logs folder with 5 files:
debug file with one debug statement.
default file with no statements.
error file with one error statement.
result file with one info statement.
warn file with one warn statement.
No fatal message, since there is no category for it.

This seems like the expected behavior to me.

**Comment by arun-awnics** [comment] 2017-11-06 10:13
Thanks for that @ramicohen303 . I have tried exactly what you said. Your code works as expected. But the same configuration doesn't work in my application. 

#### Current behavior
The log files are getting created as below:
> - logs/debug.log
> - logs/default.log
> - logs/error.log
> - logs/result.log
> - logs/warn.log

But all logs are getting logged only in `logs/default.log` file. I want to segregate like you did in your code. Kindly find my code in [my repo](https://github.com/arun-awnics/mm-node.git). 

Following is the content of my `logs/default.log` file:

```
[2017-11-06 11:49:00.458] [INFO] default - Connection established successfully for MongoDB
[2017-11-06 11:49:01.312] [INFO] default - Server started: http://localhost:3000/
[2017-11-06 11:49:01.468] [INFO] default - Connection established successfully for MySQL
[2017-11-06 11:50:32.544] [INFO] default - Connection established successfully for MongoDB
[2017-11-06 11:50:32.548] [ERROR] default - This is an error
[2017-11-06 11:50:32.550] [WARN] default - This is a warning
[2017-11-06 11:50:32.551] [FATAL] default - This is fatal message
[2017-11-06 11:50:32.703] [INFO] default - Server started: http://localhost:3000/
[2017-11-06 11:50:32.730] [INFO] default - Connection established successfully for MySQL
[2017-11-06 11:52:47.919] [INFO] default - Connection established successfully for MongoDB
[2017-11-06 11:52:47.923] [ERROR] default - This is an error
[2017-11-06 11:52:47.925] [WARN] default - This is a warning
[2017-11-06 11:52:47.927] [FATAL] default - This is fatal message
[2017-11-06 11:52:48.094] [INFO] default - Server started: http://localhost:3000/
[2017-11-06 11:52:48.149] [INFO] default - Connection established successfully for MySQL
[2017-11-06 11:54:21.468] [INFO] default - Connection established successfully for MongoDB
[2017-11-06 11:54:21.473] [ERROR] default - This is an error
[2017-11-06 11:54:21.475] [WARN] default - This is a warning
[2017-11-06 11:54:21.477] [FATAL] default - This is fatal message
[2017-11-06 11:54:21.669] [INFO] default - Server started: http://localhost:3000/
[2017-11-06 11:54:21.702] [INFO] default - Connection established successfully for MySQL
[2017-11-06 15:26:15.789] [INFO] default - Connection established successfully for MongoDB
[2017-11-06 15:26:15.794] [ERROR] default - This is an error
[2017-11-06 15:26:15.795] [WARN] default - This is a warning
[2017-11-06 15:26:15.796] [FATAL] default - This is fatal message
[2017-11-06 15:26:15.975] [INFO] default - Server started: http://localhost:3000/
[2017-11-06 15:26:16.045] [INFO] default - Connection established successfully for MySQL
[2017-11-06 15:27:45.351] [INFO] default - Connection established successfully for MySQL
[2017-11-06 15:27:45.998] [INFO] default - Connection established successfully for MongoDB
[2017-11-06 15:27:45.357] [ERROR] default - This is an error
[2017-11-06 15:27:45.359] [WARN] default - This is a warning
[2017-11-06 15:27:45.360] [FATAL] default - This is fatal message
[2017-11-06 15:27:45.999] [ERROR] default - This is an error
[2017-11-06 15:27:46.001] [WARN] default - This is a warning
[2017-11-06 15:27:46.002] [FATAL] default - This is fatal message
[2017-11-06 15:27:46.161] [INFO] default - Server started: http://localhost:3000/
[2017-11-06 15:27:46.189] [INFO] default - Connection established successfully for MySQL
[2017-11-06 15:29:33.312] [INFO] default - Connection established successfully for MongoDB
[2017-11-06 15:29:33.316] [ERROR] default - This is an error
[2017-11-06 15:29:33.317] [WARN] default - This is a warning
[2017-11-06 15:29:33.318] [FATAL] default - This is fatal message
[2017-11-06 15:29:33.456] [INFO] default - Server started: http://localhost:3000/
[2017-11-06 15:29:33.484] [INFO] default - Connection established successfully for MySQL
[2017-11-06 15:32:04.535] [INFO] default - Connection established successfully for MongoDB
[2017-11-06 15:32:04.539] [ERROR] default - This is an error
[2017-11-06 15:32:04.540] [WARN] default - This is a warning
[2017-11-06 15:32:04.541] [FATAL] default - This is fatal message
[2017-11-06 15:32:04.689] [INFO] default - Server started: http://localhost:3000/
[2017-11-06 15:32:04.723] [INFO] default - Connection established successfully for MySQL
```
And rest of the files are empty.

Thank you in advance.

**Comment by arun-awnics** [comment] 2017-11-06 17:40
Thank you very much @ramicohen303 That did solve my problem. But what do you mean by 

> copy result configuration to the default configuration?

One issue is that after I changed `var logger = log4js.getLogger();` to `var logger = log4js.getLogger('result');` , I am not getting the logs printed on my console, i.e., `type:stdout`. Why is this behavior?

One more doubt is, why should I have `result` only in `log4js.getLogger()` for it to work? If not, can I pass any other argument?

**Comment by ramicohen303** [comment] 2017-11-06 18:03
I suggest you read the documentation, it has answers for all your questions. 

In short, the parameter you pass to getLogger is the name of the category to use. The reason you don't get console messages is that the category specifies which appenders to log to, and the result category does not include the out appender, while the default category does include it. Simply add the out appender to the result category, and observe the difference.

I am closing this issue, since it is resolved.

**Closed by ramicohen303** 2017-11-06 18:03 UTC

**Comment by arun-awnics** [comment] 2017-11-07 04:34
Sure. Thanks a lot 👍
