### ISSUE TITLE
log4js version 2.10.0 is giving error when shutdown and process Exit called

### ISSUE THREAD

**Issue by DipjayDatta** [log4js-node/log4js-node#788] opened 2018-09-25 13:32 UTC
**code:**
log4js.shutdown(() => { process.exit(1); });

**Error:**
log4js.fileAppender - Writing to file ../logs/ABC.log, error happened Error: write after end
at writeAfterEnd (/node_modules/readable-stream/lib/_stream_writable.js:288:12)
at RollingFileStream.Writable.write (/node_modules/readable-stream/lib/_stream_writable.js:332:20)
at Function.app.shutdown (node_modules/log4js/lib/appenders/file.js:69:12)
at appenders.filter.forEach.a (/node_modules/log4js/lib/log4js.js:273:52)
at Array.forEach (native)
at Object.shutdown (/node_modules/log4js/lib/log4js.js:273:37)
at process.exitHandler (XYZ.js:130:12)
at emitOne (events.js:96:13)
at process.emit (events.js:188:7)
at process.exit (internal/process.js:146:15)

**Comment by nomiddlename** [comment] 2018-10-01 22:04
This issue might give you more information: #542  - the problem is that process.exit happens synchronously, before the appenders have finished their final writes. You could try adding a setTimeout call around the process.exit and waiting a second or two?

**Comment by DipjayDatta** [comment] 2018-10-04 06:45
I am calling process.exit asynchronously in shutdown callback. It not a synchronous request.

**Comment by nomiddlename** [comment] 2019-10-22 21:41
Closing this one, because as mentioned in #542 there's not a lot we can do about it.

**Closed by nomiddlename** 2019-10-22 21:41 UTC

**Comment by thernstig** [comment] 2019-10-29 15:13
@nomiddlename Could you elaborate this a bit more. In https://github.com/log4js-node/log4js-node/issues/542 the initial post says:

> has the problem that process.exit is called _asynchronously_. 

But according to https://nodejs.org/api/process.html#process_process_exit_code it is called _synchronously_. This makes that issue harder to understand, because one cannot be sure you are talking the same lingo.

**Is the real problem this?**

When the callback of `log4js.shutdown()` is called, after it has flushed it streams, calling process.exit() will be done synchronously and thus no other pending asynchronous operations should be able to occur. So how can this occur?

**Comment by nomiddlename** [comment] 2019-10-29 22:15
Yep, you're right - process.exit is synchronous and terminates any pending asynchronous operations.

**Comment by thernstig** [comment] 2019-10-30 19:39
@nomiddlename Then how is it that the original poster's concern is not valid?

If the callback of `log4js.shutdown()` is called, it means that callback is currently running on the nodejs thread. If a call to `process.exit()` then is done synchronously, how can the log4js.fileAppender in any way continue writing so that this occurs: `log4js.fileAppender - Writing to file ../logs/ABC.log, error happened Error: write after end` **?**

**Comment by nomiddlename** [comment] 2019-10-30 22:33
Is this a problem you're encountering with the latest version of log4js? If so, have you got some code that reproduces the issue? I can then see if we can fix this or not.

**Comment by ayavilevich** [comment] 2019-12-26 08:35
If you are having this issue, make sure you are not running log4js.shutdown more than once in parallel. I had such errors when I was running log4js.shutdown several times before it has time to complete the async handler.

**Comment by peteriman** [comment] 2022-01-20 06:10
#1113 fixed this issue in `log4js@6.4.0`.
