### ISSUE TITLE
Number of backup files are created different from configured in config files and some files can't open

### ISSUE THREAD

**Issue by maheshmb2007** [log4js-node/log4js-node#921] opened 2019-07-25 19:00 UTC
Hi,

In our application we have used log4js package to capture the logs. It's a great package with plenty of options. but we are facing below issues.
1. Configuration.
{
  "appenders": {
    "loglevel": {
      "type": "file",
      "filename": "log/PipelineLogs.log",
      "config.timezoneOffset": "Date().toUTCString()",
      "maxLogSize": 50000, 
      "backups": 4
    },
    "errors": {
      "type": "logLevelFilter",
      "level": "INFO",
      "appender": "loglevel"
    }
  },
  "categories": {
    "default": {
      "appenders": ["errors"],
      "level": "DEBUG"
    }
  }
}

1. Some instance it creates 6 backup files (PipelineLogs.log, PipelineLogs.log.1, PipelineLogs.log.2, PipelineLogs.log.3, PipelineLogs.log.4, PipelineLogs.log.5 and PipelineLogs.log.6) and few of them we are unable to open.
2. Some instance it created only two backup files (PipelineLogs.log and PipelineLogs.log.1).

Much appreciated for any help.

**Comment by nomiddlename** [comment] 2019-07-25 22:53
Your config looks ok to me (although I don't think the `config.timezoneOffset` option will do anything at all). Why were you unable to open some files? What were the permissions?

**Comment by maheshmb2007** [comment] 2019-07-29 21:53
Thanks for response.

All the files are having same permission, but I can only open the current log file "PipelineLogs.log", but I couldn't backup log files (PipelineLogs.log.1, PipelineLogs.log.2, etc...).
I have configured only 4 backup files, 
1. sometime it creates 6 backup files and sometime it creates only one backup file. Any Idea?

**Comment by nomiddlename** [comment] 2019-07-29 23:18
What are you using to open the files? If they have the same permissions, then why couldn't you open them? Do you get an error?

The number of backup files is dependent on the amount of logging each instance is doing - are you sure they are all doing the same amount of work?

**Comment by maheshmb2007** [comment] 2019-07-30 00:32
I tried to open log file through windows note pad and notepad++, getting the below error.
'C:\log\PipelineLogs.log.1' doesn't exist. Create it?

**Comment by maheshmb2007** [comment] 2019-08-06 18:05
Appreciate for any suggestion, any change required in my config? why its creating different number of backup file and why I am unable to open the rolled log files?

**Comment by nomiddlename** [comment] 2019-08-06 22:33
What sizes are the files you can't open? On the instances with fewer backup files, what sizes are those files?

**Comment by maheshmb2007** [comment] 2019-08-06 22:36
As I mentioned in the config files, the rolled log files around 50KB.

**Comment by nomiddlename** [comment] 2019-08-06 22:38
All the backup files are 50kb, that's good. What about the main log file?

**Comment by maheshmb2007** [comment] 2019-08-06 22:40
Main log files 5KB, but it gradually grows to 50KB and it will roll up to new backup file.

**Comment by nomiddlename** [comment] 2019-08-06 22:47
My guess for the files that you can't open is that the application is retaining a lock on the files. Try adding `"flags": "a+"`to your file appender config. That may allow reading of the files as well as writing. One way to check would be to find which processes are accessing the backup files (in unix you would use `lsof`, but I don't know what the Windows equivalent would be). 

For the instances where they are not creating many backup files, the only reason I could think of for that is that they are not doing as much work as the other instances (or potentially they could have different config).

**Comment by maheshmb2007** [comment] 2019-08-06 22:52
Appreciate for your quick response. Will try above option and get back to you. Thanks

**Comment by maheshmb2007** [comment] 2019-08-08 20:23
As you suggested I have added "flags": "a+" in config. After that it's not rolling the log files. I can see only one log file is growing more than mentioned maxLogSize. Below is the updated config.
{
"appenders": {
"loglevel": {
"type": "file",
"filename": "log/PipelineLogs.log",
"maxLogSize": 50000,
"backups": 4,
"flags": "a+"
},
"errors": {
"type": "logLevelFilter",
"level": "INFO",
"appender": "loglevel"
}
},
"categories": {
"default": {
"appenders": ["errors"],
"level": "DEBUG"
}
}
}

**Comment by nomiddlename** [comment] 2019-08-11 22:52
Other things to try are the latest version of log4js (5.0.0), or rolling back to an older version (3.0.6).

**Comment by maheshmb2007** [comment] 2019-08-12 19:23
Thanks for your response, As you suggested I have tried both 5.0.0 and 3.0.0 versions and below is the outcome.

Log4js version 5.0.0:
I got some compilation error: syntaxError: unexpected identifier at createScript…
			File: node_modules\streamroller\lib\RollingFileWriteStream.js
                                             Line: 129
Log4js version 3.0.6:	
Rolling is working fine, I could see based on my configuration I can see three backup and one main log files, out of 4 I can open all the three files, last one I couldn’t open (PipelineLogs.log.3). I am getting again files doesn’t exist error while opening.

Any thoughts?

**Comment by nomiddlename** [comment] 2019-08-12 22:33
The error on version 5.0.0 is because it needs node.js 8+, and you must be using an older version than that.

**Comment by nomiddlename** [comment] 2019-08-22 22:51
log4js@5.1.0 has some fixes for windows support. You'll need at least node 8 for it to work though.

**Comment by nomiddlename** [comment] 2019-10-04 23:42
log4js@5.2.0 fixes a file rotation bug when the files are busy.

**Comment by nomiddlename** [comment] 2019-10-15 04:10
Issue #932 was confirmed as being fixed, and I think it has the same underlying cause as your issue. I'm going to mark this as fixed in log4js@5.2.2. Please re-open if you feel this is not the case.

**Closed by nomiddlename** 2019-10-15 04:10 UTC
Labels: windows
