### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by konser80** [log4js-node/log4js-node#1171] opened 2022-01-25 13:29 UTC
After updating from 6.3.0 to 6.4.1 I've got errors.

```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);          ^

[Error: ENOENT: no such file or directory, lstat '/Users/konser/js/tools/test/trace.log'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/Users/konser/js/tools/test/trace.log'
}
```

my config:

```
  const layout = { type: 'pretty' };
  log4js.addLayout('pretty', () => formatLog4JS);
  log4js.configure({
    levels: {
      SILLY: { value: 2500, colour: 'blue' }
    },
    appenders: {
      console: { layout, type: 'stdout' },
      tracefile: { layout, type: 'dateFile', filename: 'trace.log', pattern: 'yyyy-MM-dd-hhmm00', keepFileExt: true, numBackups: 5 },
```

Error happened if I'm trying to start program, close, then wait for the next interval (in this pattern - for the next minute) and start again. So I think, It tries to rotate & write to the non-exist file.
And If I start program second time in same interval - All is OK.
Then wait for 2-3 minutes, run again and.. same error.

**Comment by konser80** [comment] 2022-01-25 13:38
UPD1: if I change 'numBackups' to 'backups': still crushing

UPD2: if I remove 'numBackups' property: still crushing

**Comment by konser80** [comment] 2022-01-25 13:52
UPD3: if I make simple pattern without any numBackups or backups properties – it keeps just 1 log :(

```      tracefile: { layout, type: 'dateFile', filename: 'trace.log', pattern: 'yyyy-MM-dd-hhmmss', keepFileExt: true },
```

**Comment by peteriman** [comment] 2022-01-25 18:55
I'm unable to run your codes at all. Can you provide a more complete snippet?

**Comment by peteriman** [comment] 2022-01-25 19:12
The following works.

```javascript
const log4js = require('log4js');
log4js.configure({
  appenders: {
    'out': { type: 'stdout' },
    'everything': { 
      type: 'dateFile', 
      filename: 'all-the-logs.log',
      pattern: 'yyyy-MM-dd-hhmmss',
      keepFileExt: true,
      numBackups: 5 // total 6 files (1 hot + 5 backups)
    }
  },
  categories: {
    default: { appenders: [ 'out', 'everything' ], level: 'debug'}
  }
});

const logger = log4js.getLogger();
let count = 1;
let timer = setInterval(() => {
  logger.warn("testing", count);
  if (count >= 10) { 
   clearInterval(timer)
  }
  count++;
}, 1000);

```

![image](https://user-images.githubusercontent.com/29530649/151043101-0d87c550-841d-4be5-b219-c3e0e45874a9.png)

**Comment by peteriman** [comment] 2022-01-25 19:15
> UPD3: if I make simple pattern without any numBackups or backups properties – it keeps just 1 log :(
> 
> ```
> tracefile: { layout, type: 'dateFile', filename: 'trace.log', pattern: 'yyyy-MM-dd-hhmmss', keepFileExt: true },
> ```
This should create 2 logs as the default `numBackups=1` which means 1 hot + 1 backup.

**Comment by konser80** [comment] 2022-01-26 16:38
Thank you for the answer. I found circular dependency in my project, it solved this problem. But i found new small bug.

```
      tracefile: {
        type: 'dateFile',
        filename: 'logs/trace.log',
        pattern: 'old/yyyy-MM/yyyy-MM-dd-hh0000',
        keepFileExt: true,
        numBackups: 5
      }
```

I use folders for old logs. And numBackups doesn't work then. It's not a problem for me - cause I save logs for 1 year and don't actually need numBackups, but for other people maybe...

**Comment by peteriman** [comment] 2022-01-27 16:24
Noted, I will mark this as invalid as per the original issue.

**Comment by peteriman** [comment] 2022-01-27 16:41
> _Originally posted by @konser80 in https://github.com/log4js-node/log4js-node/issues/1171#issuecomment-1022378915_
> I use folders for old logs. And numBackups doesn't work then. It's not a problem for me - cause I save logs for 1 year and don't actually need numBackups, but for other people maybe...

As for the side-tracked issue, would you mind raising another issue number for it?

I changed your codes a little so I can get some initial findings real quick.

```javascript
const log4js = require('log4js');
log4js.configure({
  appenders: {
    'out': { type: 'stdout' },
    'everything': { 
      type: 'dateFile', 
      filename: 'logs/trace.log',
      pattern: 'old/yyyy-MM/yyyy-MM-dd-hhmmss0000', // added seconds so can roll fast without waiting
      keepFileExt: true,
      numBackups: 5 // total 6 files (1 hot + 5 backups)
    }
  },
  categories: {
    default: { appenders: [ 'out', 'everything' ], level: 'debug'}
  }
});

const logger = log4js.getLogger();
let count = 1;
let timer = setInterval(() => {
  logger.warn("testing", count);
  if (count >= 10) { // spam 10 times (should have 10 files if not for numBackups)
   clearInterval(timer)
  }
  count++;
}, 1000);
```

Indeed, the `numBackups` doesn't work when used in such a scenario.

![image](https://user-images.githubusercontent.com/29530649/151403404-463b3ff6-947a-4fa0-a3c1-2a673ee2d2b4.png)

I will take a further look at it when I have the time. Thanks.

**Comment by peteriman** [comment] 2022-02-02 16:58
I tested with `log4js@6.3.0` (only changing `numBackups` to `daysToKeep`) and it happens as well.
While it doesn't seem to be a regression from `6.4.0`, it might still be an issue to be fixed.

**Comment by nechamireichman** [comment] 2022-02-09 12:39
we encountered  the same error:
`Error: ENOENT: no such file or directory, lstat '/var/log/next/service.log.6'`

```js
service: {
    type: 'file',
    filename: `${logDirectory}/service.log`,
    maxLogSize: 102400,
    numBackups: 5
} 
```
we suspect that it started happening since moving to version 6.4.0 (currently using 6.4.1)
@peteriman  any updates?

**Comment by peteriman** [comment] 2022-02-09 13:02
@nechamireichman, based on @konser80's reply:

> Thank you for the answer. I found circular dependency in my project, it solved this problem. But i found new small bug

.

**Comment by bdparkhurst** [comment] 2022-02-24 18:54
I also am encountering this issue with fileSync type.

        log4js.configure({
            appenders: {
                'console': { type: 'console' },
                'file': {
                    type: 'fileSync',
                    filename: './logs/application.log',
                    maxLogSize: 20000000,
                    backups: 20
                }
            },
            categories: {
                default: { appenders: ['file', 'console'], level: appenderLevel },
            }
        });

**Comment by peteriman** [comment] 2022-02-26 16:21
@bdparkhurst For which version of NodeJS and log4js?

**Comment by bdparkhurst** [comment] 2022-02-26 16:29
Node 14.19.0 / Log4Js 6.4.1

**Comment by peteriman** [comment] 2022-02-27 15:02
@bdparkhurst I managed to replicate. In my scenario, the `logs` folder does not exist and it seems like log4js does not create the folder, and it resulted in the error. By manually creating the `logs` folder (as a temporary workaround), it seems to work.

Can I check with you (if this is the same): 
1) Does your `logs` folder exist?
2) If you manually create the `logs` folder (as a temporary workaround), does the error go away?

I'll take a deeper look and ensure that `log4js` can properly create the required folders.

**Comment by peteriman** [comment] 2022-02-27 15:04
@bdparkhurst I managed to replicate. In my scenario, the `logs` folder does not exist and it seems like `log4js` does not create the folder (broken), and it resulted in the error. By manually creating the `logs` folder (as a temporary workaround), it works.

@bdparkhurst and @nechamireichman, can I check with the both of you (if this is the same as my scenario): 
1) Does your `logs` folder exist?
2) If you manually create the `logs` folder (as a temporary workaround), does the error go away?

I'll take a deeper look and ensure that `log4js` can properly create the required folders.

**Comment by peteriman** [comment] 2022-02-27 16:16
@nechamireichman Apologies, while I am able to replicate @bdparkhurst's issue (`fileSync` appender), I am unable to replicate your scenario (`file` appender). I have tested that for `file` appender, it will automatically create the folder. Would you happen to have the full stacktrace? Nevertheless, try my workaround in the comment above and let me know if it helps.

**Comment by peteriman** [comment] 2022-03-02 19:34
For clarity, there are 4 sub-issues.

- [X] 1. By @konser80 
  `Error: ENOENT: no such file or directory, lstat` (`dateFile` appender)
  Invalid due to circular dependency within his project.
- [X] 2. By @konser80 
  `numBackups` doesn't work if `pattern` consists of multi-level directories (`dateFile` appender)
  Transferred to #1196.
- [X] 3. By @bdparkhurst
  `ENOENT: no such file or directory, open` (`fileSync` appender)
  Fixed in #1191 and released in `log4js@6.4.2`.
- [ ] 4. By @nechamireichman
  `Error: ENOENT: no such file or directory, lstat` (`file` appender)
  Suspected similar to (1).

I will close this issue once all 4 sub-issues are resolved/transferred.

**Comment by peteriman** [comment] 2022-04-10 19:13
@nechamireichman, do you have any updates to the above comment?

**Comment by peteriman** [comment] 2022-04-10 19:16
@nechamireichman, do you have any updates to the above comment?

Does the issue still arise if you use `log4js@6.4.4`?

**Comment by lamweili** [comment] 2022-10-01 19:02
@nechamireichman?

**Comment by lamweili** [comment] 2022-10-31 14:13
@nechamireichman?

**Comment by lamweili** [comment] 2022-11-05 16:23
Closed due to extended period of inactivity.

**Closed by lamweili** 2022-11-05 16:23 UTC
Labels: bug
