### ISSUE TITLE
use logLevelFilter Lead to repetition out to console log

### ISSUE THREAD

**Issue by ipengyo** [log4js-node/log4js-node#861] opened 2019-04-24 12:10 UTC
config:
```
const log4jsConfig = {
    appenders: {
      console: {
        type: 'console'
      },
      "error-str": {
        type: "stderr"
      },
      "just-errors": {
        type: 'logLevelFilter',
        appender: 'error-str',
        level: 'warn'
      },
    },
    categories: {
      default:  { appenders: [ 'console', 'just-errors'], level: defaultLogLevel},
    }
  };
```

use:
```
let logger = log4js.getLogger('xxx');

logger.warn('warn test');
```

![image](https://user-images.githubusercontent.com/9323722/56658348-fe75b800-66cc-11e9-9654-9c44b9d0ca31.png)

Repeat output

---
The reason for this:

I use PM2 for the convenience of collecting error logs.

But it will cause an error to be output twice in the console.

Is there any other way to avoid optimization?

**Comment by nomiddlename** [comment] 2019-04-30 06:37
You've defined two appenders which will write to stderr - `console` and `error-str`. I think that's why you're seeing the log output twice.

**Comment by nomiddlename** [comment] 2019-05-05 22:36
Closing this one, because I think it's a configuration problem not a bug. Feel free to re-open if you have more information.

**Closed by nomiddlename** 2019-05-05 22:36 UTC
