### ISSUE TITLE
how to print line number in that file and locate the position by click?

### ISSUE THREAD

**Issue by jettangs** [log4js-node/log4js-node#844] opened 2019-03-07 08:55 UTC

**Comment by jettangs** [comment] 2019-03-07 09:02
#580 is solution，any official solution?

**Comment by nomiddlename** [comment] 2019-03-24 21:15
You should probably use [log4js-extend](https://github.com/ww24/log4js-node-extend).

Closing this one, as it is a duplicate of #791

**Closed by nomiddlename** 2019-03-24 21:15 UTC

**Comment by jettangs** [comment] 2019-03-25 08:49
> You should probably use [log4js-extend](https://github.com/ww24/log4js-node-extend).
> 
> Closing this one, as it is a duplicate of #791

it only support appending to tail of the log.
https://github.com/ww24/log4js-node-extend/issues/10
