### ISSUE TITLE
How to use log4js to log the socket.io logs

### ISSUE THREAD

**Issue by yasharma** [log4js-node/log4js-node#736] opened 2018-06-20 12:39 UTC
I was following the same approach as with expressJS
```javascript
app.use(
    loggerFactory.connectLogger(loggerFactory.getLogger('http'), {
        level: 'auto'
    })
)
```
Now for socket.io
```javascript
io.use(
    loggerFactory.connectLogger(loggerFactory.getLogger('socket.io'), {
        level: 'auto'
    })
)
```
Doing like this it throws an error:
```javascript
/User/node_modules/User-log4js/lib/connect-logger.js:243
        res.on('finish', () => {
            ^

TypeError: res.on is not a function
    at Array.<anonymous> (/User/node_modules/User-log4js/lib/connect-logger.js:243:13)
    at run (/User/node_modules/socket.io/lib/namespace.js:124:11)
    at Namespace.run (/User/node_modules/socket.io/lib/namespace.js:136:3)
    at Namespace.add (/User/node_modules/socket.io/lib/namespace.js:164:8)
    at Client.doConnect (/User/node_modules/socket.io/lib/client.js:97:20)
    at Client.connect (/User/node_modules/socket.io/lib/client.js:66:17)
    at Server.onconnection (/User/node_modules/socket.io/lib/index.js:434:10)
    at Server.emit (events.js:180:13)
    at Server.emit (domain.js:421:20)
    at Server.handshake (/User/node_modules/engine.io/lib/server.js:338:8)
    at /User/node_modules/engine.io/lib/server.js:232:12
    at Server.checkRequest (/User/node_modules/socket.io/lib/index.js:76:51)
    at Server.verify (/User/node_modules/engine.io/lib/server.js:168:17)
    at Server.handleRequest (/User/node_modules/engine.io/lib/server.js:222:8)
    at Server.<anonymous> (/User/node_modules/engine.io/lib/server.js:467:14)
    at Server.<anonymous> (/User/node_modules/socket.io/lib/index.js:343:16)
```
Seems it expecting request and response object, however socket middleware doesn't provide that one, so any help with that to pass the socket.io DEBUG logs to log4js.

Thanks

**Comment by nomiddlename** [comment] 2018-06-21 00:56
As far as I know, socket.io is not a connect-based framework. While it supports middleware, you can't just use middleware designed for other frameworks. You'd need to write a specific socket.io piece of middleware, sorry.

**Comment by nomiddlename** [comment] 2018-07-04 21:53
Going to close this one, because it's not a bug in log4js.

**Closed by nomiddlename** 2018-07-04 21:53 UTC
